### ISSUE TITLE
NEOS-27: As a Neos Administrator I want to control access to modules

### ISSUE THREAD

**Issue by johannessteu** [johannessteu/neos-development-collection#446]
Jira issue originally created by user bwaidelich:

 Atachements:

https://jira.neos.io/secure/attachment/10002/ACL_Modules.png 

 Jira-URL: https://jira.neos.io/browse/NEOS-27

**Comment by johannessteu** [comment]
Comment created by bwaidelich:

Currently it's possible to bind a Neos module to a resource via Settings.yaml:

```
TYPO3:
  Neos:
    modules:
      management:
        label: 'Management'
        # ...
        resource: 'TYPO3*Neos_Backend_Module*Management'
        submodules:
          workspaces:
            label: 'Workspaces'
            # ...
            resource: 'TYPO3*Neos_Backend_Module_Management*Workspaces'
```

This already allows the integrator to hide modules from certain roles. But the current implementation lacks some features:
- The access restriction is not configurable over the browser
- Only the complete module can be bound to resources, a more fine-grained ACL would be useful (e.g. allow role x to view the user module but only to manage roles y and z).

## TYPO3 CMS

In TYPO3 CMS the access control for modules is quite basic:

!ACL_Modules.png!
- Easy to use
- Not fine grained (only complete modules can be included/excluded)
- The parent module has to be included manually (allowing only "Web>Page" does not work, "Web" needs to be included as well)
