### ISSUE TITLE
Creating new over the structure tree doesn't respect node constraints in any cases

### ISSUE THREAD

**Issue by johannessteu** [johannessteu/neos-development-collection#702]
Jira issue originally created by user witrin:

There are the document node types `page` and `project` (custom type). The node type `page` only allows `image` in its content collection `main`. The node type `page` allows more than `image`:

```
'Vendor.Website:Project':
  superTypes: ['TYPO3.Neos:Document']
  childNodes:
    main:
      type: 'TYPO3.Neos:ContentCollection'
      constraints:
        nodeTypes:
          'Vendor.Website:Image': TRUE
          '*': FALSE
[...]
```

```
'Vendor.Website:Image':
  superTypes:
    - 'TYPO3.Neos:Content'
    - 'TYPO3.Neos.NodeTypes:ImageMixin'
    - 'TYPO3.Neos.NodeTypes:LinkMixin'
    - 'TYPO3.Neos.NodeTypes:ImageCaptionMixin'
  ui:
    label: 'Image'
    icon: 'icon-picture'
    position: 300
[...]
```

Further there are the two nodes `neos.dev` (`page`) and its child `Project` (`project`).

When load the backend with `domain/project@user-admin.html` in the browser, choose the `neos.dev` node and you click `create new` in the structure tree you only able to create an `image` node:

!1.png|thumbnail!

If you use the content canvas instead to add a child node you're able to select from all allowed child nodes:

!2.png|thumbnail!

So the action `create new` in the structure tree always use the child node constraint of that document node which was loaded with the backend first.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11727/1.png) 
![Jira Image](https://jira.neos.io/secure/attachment/11728/2.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1014
