### ISSUE TITLE
Document correct way to deactivate default NodeTypes

### ISSUE THREAD

**Issue by johannessteu** [johannessteu/neos-development-collection#841]
Jira issue originally created by user @hhoechtl:

Before 2.1 it was possible to remove default nodeTypes by doing:

``` yaml
'TYPO3.Neos.NodeTypes:Html':
  ui: <sub>
'TYPO3.Neos.NodeTypes:Form':
  ui: </sub>
'TYPO3.Neos.NodeTypes:AssetList':
  ui: <sub>
'TYPO3.Neos:PluginView':
  ui: </sub>
```

This now causes empty "Content" nodeTypes showing up in the create new dialog.
!Bildschirmfoto 2015-12-24 um 09.34.33.png|thumbnail!

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12620/Bildschirmfoto+2015-12-24+um+09.34.33.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1741
