### ISSUE TITLE
Node property help message not translated

### ISSUE THREAD

**Issue by johannessteu** [johannessteu/neos-development-collection#846]
Jira issue originally created by user @hhoechtl:

I have a node property like

```
    teaser:
      type: string
      ui:
        label: i18n
        help:
          message: i18n
```

But the help message always appears in english.
I tracked down the problem and inside the `NodeTypeConfigurationEnrichtmentAspect` when the translator is issued with the id of the help-message the locale used by the translator is always "en" instead of the backend language set by the backend user.

 Jira-URL: https://jira.neos.io/browse/NEOS-1750
