### ISSUE TITLE
Display bug in disabled selectbox editor

### ISSUE THREAD

**Issue by johannessteu** [johannessteu/neos-development-collection#877]
Jira issue originally created by user fgrell:

I have a Node with this config:

``` yaml
categoryIds:
      type: array
      ui:
        inspector:
          editorOptions:
            disabled: true
```

In the inspector the editor display white text on white background.
!neos-select2-container-disabled.png|thumbnail!

Also the options are still sortable.
!neos-select2-container-disabled2.png|thumbnail!

OS: Windows10
Browser: Google Chrome

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12907/neos-select2-container-disabled.png) 
![Jira Image](https://jira.neos.io/secure/attachment/12906/neos-select2-container-disabled2.png) 

 Jira-URL: https://jira.neos.io/browse/NEOS-1859
